version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: bundle
        target: /gems
      - type: bind
        source: ./
        target: /rubyfun
    ports:
      - 3000:3000
    command: ./start.sh

  box:
    image: busybox
    volumes:
      - "bundle:/box"
volumes:
  bundle:
